/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyThuVien;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kvan2
 */
public class BaoFrame extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    List<Bao> dataList;
    int currentPos = -1;
    /**
     * Creates new form BaoFrame
     */
    public BaoFrame() {
        initComponents();
        tableModel = (DefaultTableModel) BaoTable.getModel();
        dataList = BaoModify.getBaoList(null);
        showData();
        BaoTable.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                currentPos = BaoTable.getSelectedRow();
                idbaotxt.setText(dataList.get(currentPos).getIdBao());
                tennhaxuatbantxt.setText(dataList.get(currentPos).getTenNhaXuatBan());
                sobanphathanhtxt.setText(dataList.get(currentPos).getSoBanPhatHanh());
                ngayphathanhtxt.setText(dataList.get(currentPos).getNgayPhatHanh());
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
    }
    private void showData() {
        tableModel.setRowCount(0);
        for (Bao bao : dataList) {
            tableModel.addRow(new Object[]{
                tableModel.getRowCount() + 1,
                bao.getIdBao(),
                bao.getTenNhaXuatBan(),
                bao.getSoBanPhatHanh(),
                bao.getNgayPhatHanh()
            });
        }
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idbaotxt = new javax.swing.JTextField();
        tennhaxuatbantxt = new javax.swing.JTextField();
        sobanphathanhtxt = new javax.swing.JTextField();
        ngayphathanhtxt = new javax.swing.JTextField();
        Luubtn = new javax.swing.JButton();
        Xoabtn = new javax.swing.JButton();
        Suabtn = new javax.swing.JButton();
        TimKiembtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        BaoTable = new javax.swing.JTable();
        ext = new javax.swing.JButton();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("THÔNG TIN BÁO");

        jLabel2.setText("Id Báo:");

        jLabel3.setText("Tên Nhà Xuất Bản:");

        jLabel4.setText("Số Bản Phát Hành:");

        jLabel5.setText("Ngày Phát Hành:");

        ngayphathanhtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngayphathanhtxtActionPerformed(evt);
            }
        });

        Luubtn.setText("Lưu");
        Luubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuubtnActionPerformed(evt);
            }
        });

        Xoabtn.setText("Xóa");
        Xoabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoabtnActionPerformed(evt);
            }
        });

        Suabtn.setText("Sửa");

        TimKiembtn.setText("Tìm Kiếm");
        TimKiembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiembtnActionPerformed(evt);
            }
        });

        BaoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "IdBao", "Tên Nhà Xuất Bản", "Số Bản Phát Hành", "Ngày Phát Hành"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(BaoTable);
        if (BaoTable.getColumnModel().getColumnCount() > 0) {
            BaoTable.getColumnModel().getColumn(0).setResizable(false);
            BaoTable.getColumnModel().getColumn(1).setResizable(false);
            BaoTable.getColumnModel().getColumn(2).setResizable(false);
            BaoTable.getColumnModel().getColumn(3).setResizable(false);
            BaoTable.getColumnModel().getColumn(4).setResizable(false);
        }

        ext.setText("Thoát");
        ext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tennhaxuatbantxt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idbaotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ngayphathanhtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sobanphathanhtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TimKiembtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Luubtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Xoabtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Suabtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(reset)
                        .addGap(18, 18, 18)
                        .addComponent(ext))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idbaotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Luubtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tennhaxuatbantxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Xoabtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sobanphathanhtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Suabtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ngayphathanhtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimKiembtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ext)
                    .addComponent(reset))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ngayphathanhtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngayphathanhtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngayphathanhtxtActionPerformed

    private void LuubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuubtnActionPerformed
        // TODO add your handling code here:
        if(currentPos >=0){
            dataList.get(currentPos).setIdBao(idbaotxt.getText());
            dataList.get(currentPos).setTenNhaXuatBan(tennhaxuatbantxt.getText());
            dataList.get(currentPos).setSoBanPhatHanh(sobanphathanhtxt.getText());
            dataList.get(currentPos).setNgayPhatHanh(ngayphathanhtxt.getText());
            BaoModify.update(dataList.get(currentPos));
            currentPos = -1;
        }else{
            Bao bao = new Bao(
                idbaotxt.getText(),
                tennhaxuatbantxt.getText(),
                sobanphathanhtxt.getText(),
                ngayphathanhtxt.getText()
            );
            BaoModify.insert(bao);
            dataList = BaoModify.getBaoList(null);
        } 
        showData();
        idbaotxt.setText("");
        tennhaxuatbantxt.setText("");
        sobanphathanhtxt.setText("");
        ngayphathanhtxt.setText("");
    }//GEN-LAST:event_LuubtnActionPerformed

    private void XoabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoabtnActionPerformed
        // TODO add your handling code here:
        if(currentPos == -1) {
            JOptionPane.showMessageDialog(rootPane, "Chua chon bao can xoa, vui long kiem tra lai");
            return;
        }
        int xoa = JOptionPane.showConfirmDialog(rootPane, "Ban chac chan muon bao sach nay khong?");
        if(xoa == 0) {
            BaoModify.delete(dataList.get(currentPos).getIdBao());
            dataList.remove(currentPos);
            currentPos = -1;
            showData();
        }

        idbaotxt.setText("");
        tennhaxuatbantxt.setText("");
        sobanphathanhtxt.setText("");
        ngayphathanhtxt.setText("");
    }//GEN-LAST:event_XoabtnActionPerformed

    private void TimKiembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiembtnActionPerformed
        // TODO add your handling code here:
        String s = JOptionPane.showInputDialog("Nhap IdBao can tim kiem");
        if(!s.isEmpty()) {
            s = "%"+s+"%";
        }
        dataList = BaoModify.getBaoList(s);
        showData();
    }//GEN-LAST:event_TimKiembtnActionPerformed

    private void extActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extActionPerformed
                // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_extActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        idbaotxt.setText("");
        tennhaxuatbantxt.setText("");
        sobanphathanhtxt.setText("");
        ngayphathanhtxt.setText("");
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BaoTable;
    private javax.swing.JButton Luubtn;
    private javax.swing.JButton Suabtn;
    private javax.swing.JButton TimKiembtn;
    private javax.swing.JButton Xoabtn;
    private javax.swing.JButton ext;
    private javax.swing.JTextField idbaotxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField ngayphathanhtxt;
    private javax.swing.JButton reset;
    private javax.swing.JTextField sobanphathanhtxt;
    private javax.swing.JTextField tennhaxuatbantxt;
    // End of variables declaration//GEN-END:variables
}
