/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyThuVien;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kvan2
 */
public class SachFrame extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    List<Sach> dataList;
    int currentPos = -1;
    /**
     * Creates new form QLTVFrame
     */
    public SachFrame() {
        initComponents();
        tableModel = (DefaultTableModel) SachTable.getModel();
        dataList = SachModify.getSachList(null);

        showData();
        SachTable.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                currentPos = SachTable.getSelectedRow();
                idsachtxt.setText(dataList.get(currentPos).getIdSach());
                tennhaxuatbantxt.setText(dataList.get(currentPos).getTenNhaXuatBan());
                sobanphathanhtxt.setText(dataList.get(currentPos).getSoBanPhatHanh());
                tentacgiatxt.setText(dataList.get(currentPos).getTenTacGia());
                sotrangtxt.setText(dataList.get(currentPos).getSoTrang());
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        
    }
    private void showData() {
        tableModel.setRowCount(0);
        for (Sach sach : dataList) {
            tableModel.addRow(new Object[]{
                tableModel.getRowCount() + 1,
                sach.getIdSach(),
                sach.getTenNhaXuatBan(),
                sach.getSoBanPhatHanh(),
                sach.getTenTacGia(),
                sach.getSoTrang()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idsachtxt = new javax.swing.JTextField();
        tennhaxuatbantxt = new javax.swing.JTextField();
        sobanphathanhtxt = new javax.swing.JTextField();
        tentacgiatxt = new javax.swing.JTextField();
        sotrangtxt = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        Xoa = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SachTable = new javax.swing.JTable();
        exitbtm = new javax.swing.JButton();
        suabtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("THÔNG TIN SÁCH");

        jLabel2.setText("IdSach:");

        jLabel3.setText("Tên Nhà  Xuất Bản:");

        jLabel4.setText("Số Bản Phát Hành:");

        jLabel5.setText("Tên Tác Giả:");

        jLabel6.setText("Số Trang:");

        sobanphathanhtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobanphathanhtxtActionPerformed(evt);
            }
        });

        save.setText("Lưu");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        Xoa.setText("Xóa");
        Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaActionPerformed(evt);
            }
        });

        jButton3.setText("Tìm Kiếm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        SachTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "IdSach", "Tên Nhà Xuất Bản", "Số Bản Phát Hanh", "Tên Tác Giả", "Số Trang"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(SachTable);
        if (SachTable.getColumnModel().getColumnCount() > 0) {
            SachTable.getColumnModel().getColumn(0).setResizable(false);
            SachTable.getColumnModel().getColumn(1).setResizable(false);
            SachTable.getColumnModel().getColumn(2).setResizable(false);
            SachTable.getColumnModel().getColumn(3).setResizable(false);
            SachTable.getColumnModel().getColumn(4).setResizable(false);
            SachTable.getColumnModel().getColumn(5).setResizable(false);
        }

        exitbtm.setText("Thoát");
        exitbtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtmActionPerformed(evt);
            }
        });

        suabtn.setText("Sửa");
        suabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suabtnActionPerformed(evt);
            }
        });

        resetbtn.setText("Reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resetbtn)
                                .addGap(18, 18, 18)
                                .addComponent(exitbtm))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tennhaxuatbantxt, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idsachtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sobanphathanhtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tentacgiatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sotrangtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(suabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(348, 348, 348))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idsachtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tennhaxuatbantxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suabtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Xoa)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(sobanphathanhtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(tentacgiatxt, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(sotrangtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitbtm)
                    .addComponent(resetbtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sobanphathanhtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobanphathanhtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sobanphathanhtxtActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        if(currentPos >=0){
            dataList.get(currentPos).setIdSach(idsachtxt.getText());
            dataList.get(currentPos).setTenNhaXuatBan(tennhaxuatbantxt.getText());
            dataList.get(currentPos).setSoBanPhatHanh(sobanphathanhtxt.getText());
            dataList.get(currentPos).setTenTacGia(tentacgiatxt.getText());
            dataList.get(currentPos).setSoTrang(sotrangtxt.getText());
            SachModify.update(dataList.get(currentPos));
            currentPos = -1;
        }else{
            Sach sach = new Sach(
                idsachtxt.getText(),
                tennhaxuatbantxt.getText(),
                sobanphathanhtxt.getText(),
                tentacgiatxt.getText(),
                sotrangtxt.getText()
            );
            SachModify.insert(sach);
            dataList = SachModify.getSachList(null);
        } 
        showData();
        idsachtxt.setText("");
        tennhaxuatbantxt.setText("");
        sobanphathanhtxt.setText("");
        tentacgiatxt.setText("");
        sotrangtxt.setText("");
    }//GEN-LAST:event_saveActionPerformed

    private void XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaActionPerformed
        // TODO add your handling code here:
        if(currentPos == -1) {
            JOptionPane.showMessageDialog(rootPane, "Chua chon sach can xoa, vui long kiem tra lai");
            return;
        }
        int xoa = JOptionPane.showConfirmDialog(rootPane, "Ban chac chan muon xoa sach nay khong?");
        if(xoa == 0) {
            SachModify.delete(dataList.get(currentPos).getIdSach());
            dataList.remove(currentPos);
            currentPos = -1;
            showData();
        }

        idsachtxt.setText("");
        tennhaxuatbantxt.setText("");
        sobanphathanhtxt.setText("");
        tentacgiatxt.setText("");
        sotrangtxt.setText("");
    }//GEN-LAST:event_XoaActionPerformed

    private void exitbtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtmActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitbtmActionPerformed

    private void suabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suabtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suabtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String s = JOptionPane.showInputDialog("Nhap IdSach can tim kiem");
        if(!s.isEmpty()) {
            s = "%"+s+"%";
        }
        dataList = SachModify.getSachList(s);
        showData();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
        idsachtxt.setText("");
        tennhaxuatbantxt.setText("");
        sobanphathanhtxt.setText("");
        tentacgiatxt.setText("");
        sotrangtxt.setText("");
    }//GEN-LAST:event_resetbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SachFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SachFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SachFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SachFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SachFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable SachTable;
    private javax.swing.JButton Xoa;
    private javax.swing.JButton exitbtm;
    private javax.swing.JTextField idsachtxt;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton resetbtn;
    private javax.swing.JButton save;
    private javax.swing.JTextField sobanphathanhtxt;
    private javax.swing.JTextField sotrangtxt;
    private javax.swing.JButton suabtn;
    private javax.swing.JTextField tennhaxuatbantxt;
    private javax.swing.JTextField tentacgiatxt;
    // End of variables declaration//GEN-END:variables
}
