/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyThuVien;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kvan2
 */
public class TapChiFrame extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    List<TapChi> dataList;
    int currentPos = -1;
    /**
     * Creates new form TapChiFrame
     */
    public TapChiFrame() {
        initComponents();
        tableModel = (DefaultTableModel) TapChiTable.getModel();
        dataList = TapChiModify.getTapChiList(null);
        showData();
        TapChiTable.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                currentPos = TapChiTable.getSelectedRow();
                idtapchitxt.setText(dataList.get(currentPos).getIdTapChi());
                tennhaxuatbantxt.setText(dataList.get(currentPos).getTenNhaXuatBan());
                sobanphathanhtxt.setText(dataList.get(currentPos).getSoBanPhatHanh());
                sophathanhtxt.setText(dataList.get(currentPos).getSoPhatHanh());
                thangphathanhtxt.setText(dataList.get(currentPos).getThangPhatHanh());
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
    }
        private void showData() {
        tableModel.setRowCount(0);
        for (TapChi tapchi : dataList) {
            tableModel.addRow(new Object[]{
                tableModel.getRowCount() + 1,
                tapchi.getIdTapChi(),
                tapchi.getTenNhaXuatBan(),
                tapchi.getSoBanPhatHanh(),
                tapchi.getSoPhatHanh(),
                tapchi.getThangPhatHanh()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idtapchitxt = new javax.swing.JTextField();
        tennhaxuatbantxt = new javax.swing.JTextField();
        sobanphathanhtxt = new javax.swing.JTextField();
        sophathanhtxt = new javax.swing.JTextField();
        thangphathanhtxt = new javax.swing.JTextField();
        Luubtn = new javax.swing.JButton();
        suabtn = new javax.swing.JButton();
        xoabtn = new javax.swing.JButton();
        timkiembtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TapChiTable = new javax.swing.JTable();
        resetbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Id Tạp Chí:");

        jLabel2.setText("Tên Nhà Xuất Bản:");

        jLabel3.setText("Số Bản Phát Hành:");

        jLabel4.setText("Số Phát Hành");

        jLabel5.setText("Tháng Phát Hành");

        Luubtn.setText("Lưu");
        Luubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuubtnActionPerformed(evt);
            }
        });

        suabtn.setText("Sửa");

        xoabtn.setText("Xóa");
        xoabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoabtnActionPerformed(evt);
            }
        });

        timkiembtn.setText("Tìm Kiếm");
        timkiembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiembtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("THÔNG TIN TẠP CHÍ");

        TapChiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "ID Tạp Chí", "Tên Nhà Xuất Bản", "Số Bản Phát Hành", "Số Phát Hành", "Tháng Phát Hành"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TapChiTable);
        if (TapChiTable.getColumnModel().getColumnCount() > 0) {
            TapChiTable.getColumnModel().getColumn(0).setResizable(false);
            TapChiTable.getColumnModel().getColumn(1).setResizable(false);
            TapChiTable.getColumnModel().getColumn(2).setResizable(false);
            TapChiTable.getColumnModel().getColumn(3).setResizable(false);
            TapChiTable.getColumnModel().getColumn(4).setResizable(false);
            TapChiTable.getColumnModel().getColumn(5).setResizable(false);
        }

        resetbtn.setText("Reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        exitbtn.setText("Thoát");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(resetbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitbtn)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thangphathanhtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sophathanhtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sobanphathanhtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tennhaxuatbantxt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idtapchitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(timkiembtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Luubtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(suabtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(xoabtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel6)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(idtapchitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tennhaxuatbantxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(sobanphathanhtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(sophathanhtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(thangphathanhtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(Luubtn)
                        .addGap(18, 18, 18)
                        .addComponent(suabtn)
                        .addGap(18, 18, 18)
                        .addComponent(xoabtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timkiembtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetbtn)
                    .addComponent(exitbtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timkiembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiembtnActionPerformed
        // TODO add your handling code here:
        String s = JOptionPane.showInputDialog("Nhap IdTapChi can tim kiem");
        if(!s.isEmpty()) {
            s = "%"+s+"%";
        }
        dataList = TapChiModify.getTapChiList(s);
        showData();
    }//GEN-LAST:event_timkiembtnActionPerformed

    private void LuubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuubtnActionPerformed
        // TODO add your handling code here:
        if(currentPos >=0){
            dataList.get(currentPos).setIdTapChi(idtapchitxt.getText());
            dataList.get(currentPos).setTenNhaXuatBan(tennhaxuatbantxt.getText());
            dataList.get(currentPos).setSoBanPhatHanh(sobanphathanhtxt.getText());
            dataList.get(currentPos).setSoPhatHanh(sophathanhtxt.getText());
            dataList.get(currentPos).setThangPhatHanh(thangphathanhtxt.getText());
            TapChiModify.update(dataList.get(currentPos));
            currentPos = -1;
        }else{
            TapChi tapchi = new TapChi(
                idtapchitxt.getText(),
                tennhaxuatbantxt.getText(),
                sobanphathanhtxt.getText(),
                sophathanhtxt.getText(),
                thangphathanhtxt.getText()
            );
            TapChiModify.insert(tapchi);
            dataList = TapChiModify.getTapChiList(null);
        } 
        showData();
        idtapchitxt.setText("");
        tennhaxuatbantxt.setText("");
        sobanphathanhtxt.setText("");
        sophathanhtxt.setText("");
        thangphathanhtxt.setText("");
    }//GEN-LAST:event_LuubtnActionPerformed

    private void xoabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoabtnActionPerformed
        // TODO add your handling code here:
        if(currentPos == -1) {
            JOptionPane.showMessageDialog(rootPane, "Chua chon tap chi can xoa, vui long kiem tra lai");
            return;
        }
        int xoa = JOptionPane.showConfirmDialog(rootPane, "Ban chac chan muon xoa tap chi nay khong?");
        if(xoa == 0) {
            SachModify.delete(dataList.get(currentPos).getIdTapChi());
            dataList.remove(currentPos);
            currentPos = -1;
            showData();
        }

        idtapchitxt.setText("");
        tennhaxuatbantxt.setText("");
        sobanphathanhtxt.setText("");
        sophathanhtxt.setText("");
        thangphathanhtxt.setText("");
    }//GEN-LAST:event_xoabtnActionPerformed
    
    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitbtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
        idtapchitxt.setText("");
        tennhaxuatbantxt.setText("");
        sobanphathanhtxt.setText("");
        sophathanhtxt.setText("");
        thangphathanhtxt.setText("");
    }//GEN-LAST:event_resetbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TapChiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TapChiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TapChiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TapChiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TapChiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Luubtn;
    private javax.swing.JTable TapChiTable;
    private javax.swing.JButton exitbtn;
    private javax.swing.JTextField idtapchitxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton resetbtn;
    private javax.swing.JTextField sobanphathanhtxt;
    private javax.swing.JTextField sophathanhtxt;
    private javax.swing.JButton suabtn;
    private javax.swing.JTextField tennhaxuatbantxt;
    private javax.swing.JTextField thangphathanhtxt;
    private javax.swing.JButton timkiembtn;
    private javax.swing.JButton xoabtn;
    // End of variables declaration//GEN-END:variables
}
